accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MPL-2.0",
    "NOASSERTION",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Unlicense",
    "Zlib"
]
ignore-build-dependencies = true
ignore-dev-dependencies = true

workarounds = [
    "ring",
    "rustls",
]
